[package]
name = "rasm"
version = "0.0.1"
edition = "2021"

[dependencies]
anstyle = "1.0"
anyhow = "1.0"
clap = { version = "4.5", features = ["derive", "string"] }
rayon = "1.10.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
walkdir = "2.5"
